Heuristic Algorithms
Crystal-PISH/VolumeCalendarPlanning pull request #10
Opened 2024-05-15 16:15 UTC by Renhas

Реализовал эвристический алгоритм и иерархию стратегий IHeuristic, представляющую конкретную эвристику (сортировку работ по некоторому признаку). 

Немного изменил IAlgorithm, т.к. ICriterion не нужен в эвристических и жадном алгоритмах (они выдают одно единственное решение при заданных входных данных, там нечего проверять критерием). 

Добавил объект Solver, который используется внутри IAlgorithm (скорее всего во всех, но это не точно) для построения решения с заданным порядком работ. Т.е. схема выглядит так:
1. Находим порядок работ (не назначения по тактам, а порядок относительно друга друга!). 
    - В случае эвристик пордки зависит от выбранной эвристики. 
    - В случае жадного алгоритма порядок соответствует порядку работ в исходном массиве (то бишь он не создаёт никакого порядка, потому и жадный). 
    - В случае полного перебора мы получаем все возможные порядки работ.
2. Отдаём порядок работ в Solver. Он последовательно берёт работы из этого списка и выставляет их на первое допустимое место (не раньше раннего начала + матрица остаточных ресурсов не имеет отрицательных элементов). Это первое допустимое место и есть назначение работы.

Таким образом, IAlgorithm по сути определяет логику выделения порядка работ, а Solver уже занимается нахождением допустимого решения для заданного порядка. Скорее всего с какими-то алгоритмами это не работает, но с нашими должно работать, так что пока предлагаю оставить так.

Изменил, соответственно, BruteForce, чтобы оно собиралось вообще, но пока алгоритм там всё ещё не рабочий (это будет отдельная задача).

Добавил тестиков, перенёс тестики для моделей данных в отдельную папочку. Теста для самого эвристического алгоритма нет, т.к. нужны исходные данные задачи с решением по всем эвристикам. Зато тесты для самих эвристик (сортировок) и Solver сделал (для последних использовал пример из файлика постановки задачи)

Из эвристик реализовал сортировку работ по:
1. Ресурсоёмкости
2. Директивным срокам
3. По длительности

Добавил свой exception для случаев, когда задача не имеет решения. Solver её выбрасывает, когда не смог назначить очередную работу из списка, в самом exception можно сохранить работу, которую невозможно назначить, и текущую матрицу остаточных ресурсов (после назначения предыдущих работ).

Добавил расширения для Job и Resources, в которых засунул вычисление ресурсоёмкости и проверки на неотрицательность матрицы ресурсов. Возможно, туда же стоит пихнуть расширение работы (чтобы можно было вызвать от имени экземпляра Job) и вычитание из ресурсов работ. (Да, Саша, примерно как ты хотел, только не в матрицах 🙃 )

2024-05-15 22:43 UTC, Jopepka requested changes
Требуется переработка тестов и тестовых данных

Много где требуется переименование.

Некоторые классы непонятно реализованы

Закрыть public GetAppointment, если его публичность требуется только для тестов

 Можно избавиться от сложной структуры двух вложенных форов для перебора всех элементов DataTable, если добавить реализацию итератора для DataTable

Остальные подробности в комментариях

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Solver.cs
Решение хорошее, но функции сложные.

jobsIds соответствует "порядку работ", тогда пусть так и называется orderJobs / orderReceiptJobs

for в Solve можно заменить на foreach, будет выглядеть намного проще.

public GetAppointment, а не private так понимаю для тестирования. Это спорная тема "нужно ли тестировать приватные методы", я считаю, что надо тестировать только паблик методы, потому что они автоматически тестируют и приватные

Поля  private Resources и  private Job[] должны находиться вверху класса

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/IHeuristic.cs
IHeuristic - эвристика чего? Надо уточнить, например, IHeuristicGetOrderJobs / IHeuristicDetermineOrderJobs 

Почему функция GetSortedJobsIds включает Sorted? Он сортирует Jobs? Эвристика заключается в определении порядка работ, тогда пусть называется GetOrderJobs / GetOrderReceiptJobs / DetermineOrderJobs

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/AHeuristic.cs
Нужно уточнить название AHeuristic (см. замечание по IHeuristic)

Алгоритм не ясен, что значит ascending? Если это воспринимать прям как сортировку, то понятно, восходящая и нисходящая сортировка, но оно так не воспринимается. Да и почему целый класс эвристики зацикливается на "восходящей" и "нисходящей" сортировке?
Если оно прям нужно, тогда ладно, но не стоит усложнять этот класс этим параметром. Если требуется обратная последовательность, то можно сделать функцию "Reverse". Так много где реализована сортировка (только по возрастанию, хочешь другую - реверси).

Я бы разбил GetSortedJobsIds на большее число функций, слишком много всего делает страшного - вытаскивает какие-то id, сортирует их, затем еще и проверяет нужно ли реверсить (последнее отпадет, в принципе убрать ascending)

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/HeuristicDeadline.cs
Уточнить название класса

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/HeuristicIntensity.cs
Уточнить название класса

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/HeuristicTact.cs
Уточнить название класса

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/HeuristicAlg.cs
В название входит Heuristic, при этом в папку Heuristics он не входит. Создает непонимание почему ("Ошибся или так и задумано?"). Если подумать, то это логично, потому что этот класс не реализует эвристику, а использует ее для получения решения. Получается, что класс лучше назвать HeuristicSolution

 sortedJobsIds надо переименовать, например, orderJobs / orderReceiptJobs

2024-05-15 22:43 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/BruteForce.cs
Класс лучше назвать BruteForceSolution

2024-05-15 23:06 UTC, Renhas commented on ProjectVolumeCalendar/Models/Table/JobExtensions.cs
Можно обозвать по-другому (не Extensions, а как-то иначе), но суть тут в том, что это какие-то внешние операции с данными. Как было с матрицами и векторами. Matrix и VectorOperations - это как раз Extensions, просто названные по-другому. 

Оно вынесено за пределы класса, чтобы не загромождать сам класс, но благодаря великим прелестям шарпа, можно сделать так, чтобы эти функции вызывались от имени объекта. По сути мы решаем сразу две проблемы: 

- мы разносим внутреннюю логику (Job хранит данные, а JobExtensions определяет операции), чтобы легче было менять её; 
- мы упрощаем клиентскую логику. При использовании Job нет нужды использовать какие-то дополнительные объекты явно, ты через сам объект job можешь увидеть операции, доступные для него. При этом в момент использования тебе не нужно вообще знать о том, как устроены эти операции внутри. 

Intensity - я вообще предполагал как ресурсоёмкость (переводчик переводит ресурсоёмкость как resource intensity, resource consumption, resource capacity, можем выбрать что-то из этого), т.е. сколько всего ресурсов жрёт работа. 

По поводу строк и столбцов не совсем понял. Там в циклах нигде нет row и column. Как раз таки там везде используются resource и tact, в том числе при обращении к работе. 

По мне так вполне наглядно выглядит, когда ты обращаешься типа job[resource, tact] - то есть я получаю потребление конкретного ресурса в конкретный такт конкретной работой. 

Ты просто привязываешься к тому, что job представляется в виде таблицы, а я эти названия вводил как раз для того, чтобы забыть о том, что это таблица и оперировать понятиями ресурсов и тактов. 

Итератор - хорошая идея, но его надо тогда и в матрицы с векторами добавлять. Я думаю, это можно выделить как отдельную задачу по созданию итераторов для моделей, а не решать её при создании алгоритма. 

Нейминг с Extensions я могу поправить, но итераторы предлагаю выделить как отдельную задачу и не рассматривать её здесь.

2024-05-15 23:08 UTC, Renhas commented on ProjectVolumeCalendar/Models/Table/ResourcesExtensions.cs
По поводу нейминга, можно обозвать IsAllNonnegatively, если тебе так больше нравится. По сути это проверка того, что там нет отрицательных значений (с положительностью я перегнул, да). 

Остальное описал выше.

2024-05-15 23:11 UTC, Renhas commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/BadProblem.cs
Разумные замечания, поправлю. Не совсем понял разве что чем отличается "классы, как хранилища данных" и "классы, как хранилище конкретной задачи" - это по поводу нейминга, по поводу хранения решения вместе с исходными данными или нечто совсем другое?

Вообще, по-хорошему эти данные должны выдавать генераторы (Generators), но они у нас не определены, поэтому эти классы - временное решение, чтобы тесты хоть как-то работали.

2024-05-15 23:11 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Exceptions/NoSolutionException.cs
Понял, поправлю

2024-05-15 23:15 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Solver.cs
Нейминг поправлю, foreach тоже. Поля забыл перенести, да ;р

По поводу паблика. Оно изначально так было, ещё до тестов. Я посчитал, что будет неплохо, если solver сможет выдавать одно назначение для одной работы, а не прям для всех сразу. Можно сделать и приватной, в целом. В тестах его, кстати, нет :D

2024-05-15 23:26 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/IHeuristic.cs
Зачем уточнять, если у нас один вариант эвристик - эвристика определения порядка работ? Мне кажется, это усложнение. Названия мне не очень нравятся, ибо в них заключено действие. Раз это название класса, то оно должно определять объект, а не действие. Подумаю, чем можно заменить. 

GetSortedJobsIds сортирует индексы работ. То есть дословно оно переводится как "Получить сортированные индексы работ", просто в английском другой порядок слов. Возможно разве что s у Jobs лишняя. Выдаёт она именно индексы, а не работы, поэтому так и называется. Sorted можно заменить на Ordered, типа: GetOrderedJobIds (получить упорядоченные индексы работ) или GetJobIdsOrder (получить порядок индексов работ). 

Если вдруг возникнет вопрос - почему возвращаем индексы, а не работы? - я отвечу 🙃 :
Если возвращать отсортированные работы, то потом возникнет необходимость сопоставления отсортированной работы с изначальной, т.к. при выдаче решения (Appointments) нам нужно его выдать относительно изначального порядка работ. 

Поэтому каждый раз придётся находя назначение для работы из отсортированного списка проходиться по всему изначальному списку, выискивая изначальный индекс этой работы. Я решил, что лучше возвращать индексы, а уж если где-то понадобиться прям-таки список из отсортированных работ, то можно будет его в отдельном месте составить, имея индексы и изначальный список.

2024-05-15 23:40 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/AHeuristic.cs
"Да и почему целый класс эвристики зацикливается на "восходящей" и "нисходящей" сортировке" - потому что у нас нет других эвристик. ВСЕ наши эвристики - сортировки порядка работ. Если будут другие эвристики - их реализация будет в других классах и это уже будет другой задачей. 

Вариативность в плане порядка я добавил, чтобы было больше вариантов эвристик (в два раза считай) для последующего сравнения на задачах. 

Сделать Reverse? Как? Это иерархия - стратегии, они ничего не хранят (кроме bool), более того, предполагается, что ими всеми будут пользоваться одинаково без знания о том, как именно они сортируют. То есть где-то ВНЕ алгоритма создаётся эвристика-сортировка (либо восходящая, либо нисходящая, алгоритм об этом НЕ знает), а алгоритм просто даёт ей работы и получает индексы. 

Если, предположим, делать отдельную функцию Reverse, которая вызовет GetSortedJobsIds и реверснит массив, то где эта функция будет вызываться? В алгоритме вместо GetSortedJobsIds? Не может такого быть, алгоритм не должен об этом знать.

Алгоритм должен взять работы, передать их в GetSortedJobsIds и получить индексы, он больше ничего не должен делать с объектом-эвристикой, поэтому непонятно где именно это всё будет ревёрситься. Можно создать отдельные классы, но это плохо, ибо классовый взрыв. Не вижу ничего плохого в том, чтобы стратегия хранила состояние, которое описывает её поведение. 

Разбить можно, но это лишь добавит кода, там также будут те же строчки, просто вместо LINQ будут вызовы функций. А делает она по сути очень простые вещи - преобразует массив Job'ов в массив индексов, сортирует индексы и возвращает в нужном виде. Если очень хочется, могу разнести на 2-3 функции разные, хотя не вижу смысла.

2024-05-15 23:45 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/HeuristicAlg.cs
Heuristic в название входит, т.к. это эвристический алгоритм, просто это общий вид эвристического алгоритма, который уже может сконфигурирован конкретной эвристикой.

Папка Heuristics хранит эвристики, HeuristicAlg представляет эвристический алгоритм. По-моему нет проблем. HeuristicSolution звучит как название решения, но никак не алгоритма (!). 

"этот класс не реализует эвристику" - а он и не должен. Он реализует эвристический алгоритм, а не конкретную эвристику, поэтому он и называет HeuristicAlg (можно дополнить до Algorithm, если очень хочется).

2024-05-15 23:47 UTC, Renhas commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/BruteForce.cs
Solution - решение, а это алгоритм. Можно переименовать в BruteForceAlgorithm, но как будто в этом нет смысла, ибо BruteForce'ом называют именно алгоритм и других значений у него вроде как нет (прямое не берём, оно неприменимо в контексте решения задача планирования)

2024-05-16 10:33 UTC, Jopepka commented on ProjectVolumeCalendar/Models/Table/JobExtensions.cs
1. Если Job - хранилище данных, а JobExtension - операции, тогда пусть по аналогии с MatrixOperations будет называться JobOperstions.
2. Если Intensity заменить на ресурсоемкость (resource intensity), то станет понятнее. Можно буквально перевести "Сумма ресурсов", мне кажется так даже лучше будет.
3. Оставляем job[resource, tact], надо просто чуть чуть привыкнуть
4. Итератор выделяем как отдельную задачу, но потом добавить переработку кода с его использованием

И не в тему, мне кажется, что от сахара шарпа (вызов функции от имени объекта) могут быть потом проблемы, потому что мы используем функции объекта так, будто это их функции, а по факту это другой класс делает. Но хз, может и норм, по крайней мере получается правда красиво

2024-05-16 10:38 UTC, Jopepka commented on ProjectVolumeCalendar/Models/Table/ResourcesExtensions.cs
Мне кажется тогда лучше IsAllValuePositive или IsAllValueNonnegatively. Мне и Value не особо нравится, надо как то указать, что ячейки положительны. Если обозвать Cell, то идет абстракция к таблицам, а ты хотел от этого уйти

2024-05-16 10:45 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/BruteForce.cs
Алгоритм для чего? Что является результатом полного перебора? Ладно если бы он реализовывал как то абстрактно полный перебор любого массива, но он же также как и HeuristicAlg выдает конкретное решение, только методом полного перебора

2024-05-16 10:52 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/HeuristicAlg.cs
Так а разве все то, что лежит в папке Heuristics не является алгоритмами для получения каких-то перестановок (очереди работ)? 

"HeuristicSolution звучит как название решения" - он должен звучать так, чтобы понятно было что он делает, а этот класс как раз использует эвристику для получения решения. "HeuristicAlg" звучит же так, будто это какой-то конкретный алгоритм, да и не понятно, что является результатом

К тому Alg или Algorithm, не имею ничего против Alg, такое обозначение ассоциируется только с алгоритмом

2024-05-16 11:04 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Heurestics/IHeuristic.cs
1. Может не самые удачные названия привел, но все равно не понятно эвристики чего. 
2. Сортировка ассоциируется с сортировкой по возрастанию или убыванию. Когда видишь код, создается ощущение, что именно это и происходит "зачем-то отсортировали работы, наверно, чтобы применить потом эвристику", то есть потом ожидаешь, что вызовется какой-то getHeuristicResult. По крайней мере, когда я смотрел код, я не понял зачем ты сортируешь работы
3. Я так и предполагал, что там какие то траблы и проще возвращать индексы, норм.

2024-05-16 11:35 UTC, Jopepka reviewed
Все отлично!

Есть пара предложений по неймингу, есть синтаксическая ошибка в двух класса (в функции слово матрица не правильно написано)

В AJobIdsSorting можно Sort разделить на две функции AscendingSort и DescendingSort

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForCorrectProblem.cs
> +    public static Resources InitResources => new(GetResourceMatrix());
Можно без Init, просто Resources

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForCorrectProblem.cs
> +    public static Appointments Expected => new([0, 2]);
ExpectedAppointments, потому что код var expected = DataForCorrectProblem.expected() не говорит, что мы ожидаем и проверяем назначения

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForCorrectProblem.cs
> +    private static IMatrix[] GetJobMatrces() => [
Синтаксическая ошибка  GetJobMatrces, должно быть GetJobMatrices

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForWrongProblem.cs
> +    public static Resources InitResources => new(GetResourceMatrix());
Можно без Init, просто Resources

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForWrongProblem.cs
> +    private static IMatrix[] GetJobMatrces() => [
Синтаксическая ошибка в названии функции

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Sortings/AJobIdsSorting.cs
Так намного лучше! Теперь понятно что делают эвристики. Можно так и оставить. 
Правда принимать в конструкторе ascending все равно выглядит не красиво... Предлагаю такое решение - две функции AscendingSort, DescendingSort (или же SortByAscending и SortByDescending). Вторая будет вызывать первую и реверсить ее

2024-05-16 11:35 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Extensions/CollectionsExtensions.cs
Ты это уже где то применил? Если да, то это хорошее решения, я даже не заметил. И может изменить toIds, на getIds?

2024-05-16 21:06 UTC, Jopepka approved these changes

2024-05-16 21:08 UTC, merged