Greedy and BruteForce
Crystal-PISH/VolumeCalendarPlanning pull request #19
Opened 2024-05-30 06:19 UTC by Renhas

Изменил реализацию жадного алгоритма, теперь он итеративный, как и полный перебор. 

Поменял структуру файликов у алгоритмов. Разнёс алгоритмы по дополнительным папочкам, JobAssigner вынес из алгоритмов в целом. 

Часть логики из JobAssigner'а вынес в новый класс AppointmentFinder, который ищет назначение для одной работы (а не для списка) и, при желании, сохраняет матрицу остаточных ресурсов (да, немножечко нарушение srp, но я не придумал решения лучше, без перерасчёта residual вне цикла и возвращения кортежа). 

Так как жадный алгоритм сортирует работы по остаточным тактам, добавил работам TactsReserve, помимо TactsDelay. Последний переписал через TactsReserve. 

Добавил тестиков к жадному алгоритму и полному перебору. Надо будет потом добавить тесты для разных критериев у полного перебора, да и в целом какие-то хитрые задачи подобрать, но пока решил оставить простые тесты в качестве первого приближения, так сказать.

2024-05-30 10:31 UTC, Jopepka requested changes

2024-05-30 10:31 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/Algorithms/Iterative/GreedyAlg.cs
Если AppointmentFinder станет интерфейсом, то тут надо изменить на использование интерфейса

вынести Array.IndexOf(_jobs, bestJob) либо в расширение массивов, либо в временную переменную выше (я бы и то и другое сделал)

FindBestJob можно перенести в наследника, потому что его реализация может быть разной.

копирование состояния можно написать в одну строчку

2024-05-30 10:31 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/JobAssigners/AppointmentFinder.cs
Стоит сделать интерфейс. 

Лучше переименовать _residual в _residualResources.

От saveResidual надо как то избавиться... Потому что даже разделение на FindAppointment и FindAppointmentAndSaveResudal будет лучше в использовании (хотя название у второго ужасное, почему при поиске назначения еще и сохраняем остатки)
А вообще эта проблема наталкивает на то, что класс нарушает srp. Он должен либо находить назначение в переданных ресурсах, либо вычислять из ресурсов работу

2024-05-30 10:31 UTC, Jopepka commented on ProjectVolumeCalendar/CalendarPlain/JobAssigners/JobAssigner.cs
Если AppointmentFinder отнаследуется от интерфейса, то надо тут заменить на интерфейс

2024-05-30 13:46 UTC, Renhas commented on ProjectVolumeCalendar.Tests/AlgorithmsTests/TestData/DataForFirstCase.cs
В случае ресурсов это было сделано, насколько помню, во избежание ругательств со стороны линтера, которому не нравится большая вложенность. 

В случае работ я уже не помню, может тоже из-за линтера, может для единообразия. В целом, можно содержимое функции сразу пихнуть в _matricesForJobs, но как будто удобнее, чтобы все матрицы были в одном месте, друг с другом.

2024-05-31 12:18 UTC, Jopepka approved these changes
Good!

2024-05-31 12:18 UTC, merged